using System.IO;
using System.Numerics;
using System.Threading.Tasks;
using Content.Client.Interactable;
using Content.Shared.ActionBlocker;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Containers;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BaseButton;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client._Impstation.Toys.FakePuddle.UI;
[GenerateTypedNameReferences]
public sealed partial class FakePuddleMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IFileDialogManager _dialogs = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    public EntityUid Entity;

    public FakePuddleMenu()
    {
        RobustXamlLoader.Load(this);
        // IoCManager.InjectDependencies(this);
        // MinSize = SetSize = new Vector2(400, 150);
    }

    public void UpdateState()
    {
        
    }
}